### ISSUE TITLE
How can I execute the BreezyCreate2 code from website?

### ISSUE THREAD

**Issue by papablank** [simondlevy/BreezyCreate2#2]
First of all I want to thank you so much for contributing to this BreezyCreate2 code. I'm a student at Northcentral Technical College in Wisconsin and I'm using the Create2 for my final project in the Electromechanical Technology program. I came across your code and was able to install it (took me a while but it was worth it!) and am now controlling my Create2 using python which is awesome. I am also using the create2api by pomeroyb.

Here is my issue: I am very new to programming in Python, and have some experience making websites. I would like to run your BreezyCreate2 code on my RaspberryPi 3 to make my robot move via a web interface. There is almost no documentation or videos out there on doing this - or else I am too much of a noob to find it.

Can you point me in the right direction toward a web development tool that will allow me to interface with your code on the Rpi ?

**Comment by simondlevy** [comment]
I'm delighted you got it working!  Unfortunately, browser-side control is out of my expertise area. You'd probably have to write some Javascript to talk to the RaspberryPi over a standard wifi connection or perhaps wireless serial modem like XBee.  Beyond that I have no idea.
