### ISSUE TITLE
unpack requires a buffer of 1 bytes

### ISSUE THREAD

**Issue by kyleddm** [simondlevy/BreezyCreate2#3]
most of the time I try and get the sensor information, I receive an error; "umpack requires a buffer of 1 bytes."  I am running breezycreate 2 using python3 on a Raspberry Pi model 3+

**Comment by tatesnow** [comment]
I have the same problem with you

**Comment by GaganBhat** [comment]
@kyleddm @tatesnow have either of you figured out a solution to this yet? Does switching to python 2 work?

**Comment by kyleddm** [comment]
I stepped back from this project for now, so I haven't tried to solve it since I posted.
